spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  h2:
    console:
      enabled: true
  show-sql: true
  datasource:
    url: jdbc:h2:mem:cars
    username: sa
    password:
    driverClassName: org.h2.Driver